services:
    wandi.easy_admin.command.user.create:
        class: Wandi\EasyAdminBundle\Command\UserCreateCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin:user:create }
    wandi.easy_admin.command.user.change_password:
        class: Wandi\EasyAdminBundle\Command\UserChangePasswordCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin:user:change-password }
    wandi.easy_admin.command.user.enable:
        class: Wandi\EasyAdminBundle\Command\UserEnableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin:user:enable }
    wandi.easy_admin.command.user.disable:
        class: Wandi\EasyAdminBundle\Command\UserDisableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin:user:disable }
